name: Test Action
on:   
  workflow_dispatch:
  push:
    branches: 
      - main    
jobs: 
  linux_test:
    runs-on: ubuntu-latest
    name: Linux Test Job
    steps:
    - name: Linux Test Info
      uses: zio3/discord-webhook-notify@v1
      with:
        severity: info
        details: Test succeeded.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Warn
      uses: zio3/discord-webhook-notify@v1
      with:
        severity: warn
        details: Test warning.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Error
      uses: zio3/discord-webhook-notify@v1
      with:
        severity: error
        details: Test error.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Custom
      uses: zio3/discord-webhook-notify@v1
      with:
        severity: info
        username: CustomUsername
        color: '#ff00aa'
        avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
        description: This is a custom description.
        details: 'Custom details: Somebody set up us the bomb.'
        footer: This is a footer.
        text: This is where text goes.
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Success
      uses: zio3/discord-webhook-notify@v1
      if: success()
      with:
        severity: info
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Failure
      uses: zio3/discord-webhook-notify@v1
      if: failure()
      with:
        severity: error
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    - name: Linux Test Cancelled
      uses: zio3/discord-webhook-notify@v1
      if: cancelled()
      with:
        severity: warn
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
